### ISSUE TITLE
Not showing any articles in WSL

### ISSUE THREAD

**Issue by iamjohnnyli** [0x-jerry/vscode-hexo-utils#39]
**Describe the bug**
The VS Code extension works great in Windows environment, but when I set VS Code to remote to WSL, I can't get any article.
![image](https://user-images.githubusercontent.com/5987932/109579853-876e8f00-7aae-11eb-999a-8389e856be24.png)

I didn't set up ```Hexo: Hexo Project Root```, and I have tried reinstall the extension.

**Plugin version(please complete the following information):**
v0.1.21

**Comment by hello-go-maker** [comment]
I do

**Comment by cwxyz007** [comment]
> I do

Do you want to contribute this feature ? If yes, that should be very thankful. because recently, I don't have enough time to do this.

**Comment by iamjohnnyli** [comment]
@cwxyz007 我同时也想试试，我估计是路径问题。不过我一直写python的，希望自己能帮上点点吧
