### ISSUE TITLE
能否增加post搜索过滤和新建post后，自动打开post，并在post列表中高亮显示该post.....

### ISSUE THREAD

**Issue by sirliu** [0x-jerry/vscode-hexo-utils#43]
能否增加

- post搜索过滤功能，post列表文章多的时候找文章是个头疼的事！

- 新建`post`后，自动打开`post`，并在`post`列表中定位并高亮显示该`post`，目前高亮显示的是`最后一个打开`的`post`，即使该`post`编辑页面关闭了还是高亮显示。

- 能不能实现：把post从一个分类（或标签）拖动到另外一个分类（或标签）里面，post的Front Matter作出相应改变。

我知道我的要求的有点多了........
这扩展是我找了好几天来最最最喜欢的hexo辅助了，真香！！！！

**Comment by 0x-jerry** [comment]
搜索功能建议直接用 `control + p` 或者 `command + p` 功能来筛选

新建之后自动打开，这个功能不错，后续支持。

拖拽目前无法实现，因为 `vscode` 插件不支持拖拽功能，详见 https://github.com/Microsoft/vscode/issues/32592

**Comment by 0x-jerry** [comment]
> 即使该post编辑页面关闭了还是高亮显示

关于这一点，`vscode` 自己的文件列表也是这种处理方式。

**Comment by sirliu** [comment]
> > 即使该post编辑页面关闭了还是高亮显示
> 
> 关于这一点，`vscode` 自己的文件列表也是这种处理方式。

我刚刚也发现了这一点，准备回来撤走这一点，结果发现你已经回复了！感谢~
