### ISSUE TITLE
路过图床更换域名导致上传失败

### ISSUE THREAD

**Issue by sirliu** [0x-jerry/vscode-hexo-utils#44]
如题。路过图床域名由imgchr.com改为imgtu.com，导致自动上传失败，虽然我通过修改插件本地`js`已经正常使用，但是其他使用插件的人会遇到同样的情况。
如果插件自带的代码片段能够作为设置项自定义，那将更完美（虽然VSCODE自带代码片段能够实现并云端同步）。
另外，我正在写一个关于该插件的[小白入门文章](https://sirliu.github.io/2021/8/vscode-hexo-utils%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/)，希望得到答疑，比如：

1. `Hexo: Generate Time Format`设置项可以设置的格式是怎样的；
2. `Hexo › Markdown: Resource`这个设置貌似没有实际意义，至少我没有发现。
3. 能不能实现在`Hexo: Hexo Project Root`下设置`Hexo`项目路径，然后可以在VSCODE不打开`Hexo`项目的情况下直接点击侧栏按钮就能进行博客文章管理吗

**Comment by 0x-jerry** [comment]
感谢反馈！

> 路过图床域名由imgchr.com改为imgtu.com

这个问题，如果你愿意的话，可以提一个 PR，我稍后合并即可。

关于这三个问题：

1. 时间格式参考 [dayjs.format](https://day.js.org/docs/en/parse/string-format)
2. 这个配置项会开启代码中的 `markdown` 插件，用于支持一些 `hexo` 自己的语法，例如 [hexo asset folders](https://hexo.io/zh-cn/docs/asset-folders)
https://github.com/0x-jerry/vscode-hexo-utils/blob/563251e86c53157c0b052463ddd24e7d5a427d67/src/extension.ts#L39-L45

3. 理论上可以实现

**Comment by 0x-jerry** [comment]
关于自定义代码片段，建议用 `vscode` 自带的代码片段功能，`vscode` 可以给每个项目设置代码片段，详情参考 [vscode create snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets)

因为在这个插件里面实现这样一个功能，用的人应该不会很多，这也不是这个插件该做的事情。

**Comment by sirliu** [comment]
> 关于自定义代码片段，建议用 `vscode` 自带的代码片段功能，`vscode` 可以给每个项目设置代码片段，详情参考 [vscode create snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets)
> 
> 因为在这个插件里面实现这样一个功能，用的人应该不会很多，这也不是这个插件该做的事情。

嗯嗯，也确实是，没必要重复造轮子。

**Comment by sirliu** [comment]
> 感谢反馈！
> 
> > 路过图床域名由imgchr.com改为imgtu.com
> 
> 这个问题，如果你愿意的话，可以提一个 PR，我稍后合并即可。

没必要新起一个PR吧，只需要将此行的`imgchr.com`改为`imgtu.com`就OK了。https://github.com/0x-jerry/vscode-hexo-utils/blob/563251e86c53157c0b052463ddd24e7d5a427d67/src/uploader/Imgchr.ts#L16

**Comment by sirliu** [comment]
额....不好意思，刚刚在折腾hexo博客的云端编写环境，使用coding的`cloud studio`（即网页版vscode），“离线”安装了vscode-hexo-utils插件，但是貌似不起作用，不知道哪里出问题了，按理说应该是一样的。

**Comment by 0x-jerry** [comment]
@sirliu 目前没有专门的日志，不过可以看看 `vscode` 插件加载的相关日志，如果是插件启动相关错误，都是可以看到的。

![image](https://user-images.githubusercontent.com/14226737/130437777-6b36449b-99d2-4259-aeee-d88830967413.png)

**Comment by 0x-jerry** [comment]
我先把这个 issue 关了，如果有其他问题，请另开一个 issue 讨论 ～
