### ISSUE TITLE
某些情况下 与  vscode-paste-image 冲突

### ISSUE THREAD

**Issue by yiyungent** [0x-jerry/vscode-hexo-utils#45]
**Describe the bug**

我需要将图片保存在 与 当前正在编辑的文件名 相同名的文件夹下，于是使用 `vscode-paste-image`，
如此设置 

![image](https://user-images.githubusercontent.com/16939388/149517657-7b363a1e-2e03-4ae9-89d9-e93477868c9a.png)

，但启用此插件后,

```
![2022-01-14T204837](2022-01-14T204837.png)
```

禁用 `vscode-hexo-utils` 后就正常了 

```
![](marktext-notebook/2022-01-14-20-42-22.png)
```

**To Reproduce**
1. Install vscode-paste-image
如下设置
![image](https://user-images.githubusercontent.com/16939388/149517657-7b363a1e-2e03-4ae9-89d9-e93477868c9a.png)

2. Install vscode-hexo-utils , 重启 vscode

3. 截图, `Ctrl+Alt+V`

**Expected behavior**

```
![](marktext-notebook/2022-01-14-20-42-22.png)
```

**Screenshots**

**Plugin version(please complete the following information):**

fantasy.vscode-hexo-utils v0.1.27
mushan.vscode-paste-image v1.0.4

**Additional context**

**Comment by 0x-jerry** [comment]
你可以打开 vscode 的快捷键设置，清除 hexo.paste 快捷键，这样就不会冲突了。

![image](https://user-images.githubusercontent.com/14226737/149521808-9818d718-ec8f-41ff-8732-d0aa65ec2e1b.png)

**Comment by yiyungent** [comment]
不得不说，感谢，这是个好方法
