### ISSUE TITLE
Extension breaks Markdown Preview regarding Images

### ISSUE THREAD

**Issue by kristofzerbe** [0x-jerry/vscode-hexo-utils#46]
**Describe the bug**
Don't know why, but the default VSCode Markdown preview (and others) was not able to preview images with relative paths. After disabling all extensions one by one, I discovered, that the images are shown only, when **vscode-hexo-utils** is disabled.

**To Reproduce**
1. Enable vscode-hexo-utils
2. Create Markdown file
2. Store an image in the same folder, f.e. ``my-image.png``
2. Write ``![description](my-image.png)`` in MD file
3. Click on PREVIEW button

**Expected behavior**
Image should be shown in preview

**Plugin version(please complete the following information):**
latest

**Comment by 0x-jerry** [comment]
Fixed, please upgrade and try again. And thanks for your feedback.
