### ISSUE TITLE
不显示categories

### ISSUE THREAD

**Issue by CCandle** [0x-jerry/vscode-hexo-utils#48]
环境：
- OS: Ubuntu 20.04.3 LTS
- hexo: 6.1.0
- hexo-theme-kaze: ^1.0.5
BUG:侧栏中，post，draft，tags都正常，而categories中没有显示

front-matter 示例：
```
---
title: Git 分支管理策略
date: 2021-11-07T03:05:08+08:00
tags:
    - Git
category:
    - 开发工具
excerpt: Git是一个强大的多分支版本管理软件。好的分支策略能发挥它最大的效用——多人协作开发。当然，单人开发时拥有好的分支管理策略也对项目有着巨大的帮助。
---
```
![image](https://user-images.githubusercontent.com/45314580/164982164-58f36f8a-77af-44b8-8f44-67152dd51a4f.png)
附上tree目录
http://[preview.blog.ccandle.top/tree.txt](http://preview.blog.ccandle.top/tree.txt)*（临时链接）*

**Comment by 0x-jerry** [comment]
插件识别的是 `categories`，不是 `category`

```md
---
categories:
    - 开发工具
---
```

**Comment by 0x-jerry** [comment]
Hexo 预定义的参数也是 `categories `，https://hexo.io/zh-cn/docs/front-matter.html
