### ISSUE TITLE
MacBook m1 12.6.1 (21G217) 安装了扩展，设置了地址，无法使用报错

### ISSUE THREAD

**Issue by x420520** [0x-jerry/vscode-hexo-utils#62]
运行命令 hexo.refresh[post] 错误: command 'hexo.refresh[post]' not found。这可能是由提交 hexo.refresh[post] 的扩展引起的。

**Comment by 0x-jerry** [comment]
目前这个插件，默认是不启用的。

这个插件在检测到任何 `_config.yml` 文件后才会启用。

https://github.com/0x-jerry/vscode-hexo-utils/blob/0d2e3d578da21d6a5421b02ff48b568a2b33a909/package.json#L29-L31
