### ISSUE TITLE
启用扩展后无法预览markdown文件

### ISSUE THREAD

**Issue by Kenxu2022** [0x-jerry/vscode-hexo-utils#98]
**Describe the bug**
在更新到vscode v1.94.0后，无法使用插件预览markdown文件，预览区域无法显示任何内容，同时出现报错：Cannot read properties of undefined (reading 'path')。禁用插件后可以预览

**Plugin version:**
v0.4.1

**Additional context**
vscode详细信息：
版本: 1.94.0 (user setup)
提交: d78a74bcdfad14d5d3b1b782f87255d802b57511
日期: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by 0x-jerry** [comment]
感谢反馈！可以提供一下可复现的仓库吗？因为我自己没有复现出来。

**Comment by Kenxu2022** [comment]
我新建了一个文件测试了一下，在只有文字的情况下功能一切正常，但是在插入图片后便无法预览整个markdown文件  
这是在禁用所有插件的情况下，预览一切正常：  
![](https://github.com/user-attachments/assets/f8a2864b-7242-469f-b9bd-61fb5611c49a)  
在开启Hexo Utils插件后，markdown文件无法预览：  
![](https://github.com/user-attachments/assets/6e6a141c-d528-4b61-970f-762b0e1821c7)  
同时出现报错：  
![](https://github.com/user-attachments/assets/34881c1a-5f6f-47db-a045-aacfe357fa66)

**Comment by 0x-jerry** [comment]
这种情况只会出现在单独打开 md 文件的时候，v0.4.2 版本已兼容这种情况。再次感谢反馈~

**Comment by Kenxu2022** [comment]
感谢作者的快速修复，现在普通文件没有问题了，但是博客markdown文件中的所有图片都无法显示了。  
说一下我的使用环境：我在一台linux服务器上配置好了hexo，再通过vscode的ssh远程连接在服务器上写作与预览。同时，我开启了hexo的```post_asset_folder```选项，图片资源都存放在与文章同名的文件夹内  
现在使用```ctrl+alt+v```可以正常粘贴图片文件至文件夹内，但无法预览图片，如下图：  
![屏幕截图 2024-10-06 193314](https://github.com/user-attachments/assets/b2fea80c-c202-4fe8-b6d1-0f610a0d0b88)  

猜测：不知道这个问题是否跟[vscode切换架构](https://code.visualstudio.com/updates/v1_94#_esm-is-shipping-for-vs-code)有关？我安装的另一个插件[vscode-background](https://github.com/shalldie/vscode-background)在更新到vscode v1.94后也出现了问题，详见：shalldie/vscode-background#467 shalldie/vscode-background/pull/466
(PS:我的博客仓库是https://github.com/Kenxu2022/Blog ,但里面都是生成的静态文件，应该没啥用)

**Comment by 0x-jerry** [comment]
从你的截图来看，应该是没有开启 vscode-hexo-utils 插件，正常开启状态，会有一个侧边栏。
![image](https://github.com/user-attachments/assets/2abbea59-50c5-441d-9dfa-d7c053e85b6e)

**Comment by 0x-jerry** [comment]
0.4.3 版本已支持 remote workspace，但是需要安装这个插件在服务器上

![ssh](https://github.com/user-attachments/assets/a37a492c-86ef-4753-b0ce-5fb985226c13)

**Comment by Kenxu2022** [comment]
> 从你的截图来看，应该是没有开启 vscode-hexo-utils 插件，正常开启状态，会有一个侧边栏。 ![image](https://private-user-images.githubusercontent.com/14226737/373952170-2abbea59-50c5-441d-9dfa-d7c053e85b6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNTc3ODgsIm5iZiI6MTcyODI1NzQ4OCwicGF0aCI6Ii8xNDIyNjczNy8zNzM5NTIxNzAtMmFiYmVhNTktNTBjNS00NDFkLTlkZmEtZDdjMDUzZTg1YjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIzMzEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YTBhMjBmN2UxZjg2MjczOTM4ZjRmYjEyYzcwZjE2ODU3OGQxNDU5MTAwZGZlYTRhNTg5YmUxMDc3ZDZiYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YmnFToFA-maCnQfnKx_PO449nWSOhyx4nev9J7tugzs)
> 
> 另外，这个插件通过 ssh 连接服务器使用，的确会存在图片无法正常显示。

首先还是感谢作者的关注，这里其实是开启了插件的，只是我手动隐藏了（反正点进去啥也不会显示😂）  

在更新到最新版本后，```_posts```文件夹内文章的图片显示正常了，但```_drafts```文件夹内文章的图片依然无法显示。同时新的问题出现了：无法使用```ctrl+alt+v```从剪贴板粘贴图片。该功能上一个版本是正常的，这个版本出现报错：```Hexo: EntryNotFound (FileSystemError): File to move/copy does not exist```（剪贴板里没有图片也是这个报错，会不会是插件没有找到图片？）

此外还发现了两个小Bug（均在侧边栏操作）：  
1. ```_posts```和```_drafts```文件夹之间互相移动时不会移动资源文件夹  
2. 无法重命名文章

PS：最新版本Hexo Utils侧边栏可以正常显示文章草稿等内容了，但必须将hexo所处的文件夹放在第一个打开的位置，似乎插件会将第一个打开的文件夹认为是hexo所处的文件夹，如果第一个文件夹不是hexo所处的文件夹则依然不会显示任何内容，如下图：  
![屏幕截图 2024-10-07 082410](https://github.com/user-attachments/assets/af529c42-e891-4bb2-901d-649e75eb1548)  
![屏幕截图 2024-10-07 082522](https://github.com/user-attachments/assets/e0d09740-7c08-497c-a6c6-d8628cd27937)

**Comment by 0x-jerry** [comment]
> PS：最新版本Hexo Utils侧边栏可以正常显示文章草稿等内容了，但必须将hexo所处的文件夹放在第一个打开的位置，似乎插件会将第一个打开的文件夹认为是hexo所处的文件夹，如果第一个文件夹不是hexo所处的文件夹则依然不会显示任何内容

目前的确只会处理第一个文件夹

**Comment by 0x-jerry** [comment]
昨天只是简单处理了一下，没想到这么多问题，之前的确没有测试过通过 ssh 连接服务器的方式来使用这个插件 😫。后续可以在对应的 issue 下追踪一下，分别为：
- #101 
- #102 
- #103

**Comment by Kenxu2022** [comment]
感谢作者的修复，目前使用ssh连接的问题还是比较多，我暂时回退到之前的smb+nextcloud同步到本地的方法撰写博客。目前还有一个问题：无论是本地还是remote workspace```_draft```文件夹中的图片都无法显示，希望作者关注一下。
